server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    server-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: gateway-server

#  cloud:
#    gateway:
#      routes:
#        - id: 1st-service
##          uri: http://localhost:52148/
#          
#          # ??? ? ???? ??? application name ??(??? ??? ???? ??? ?)
#          uri: lb://1ST-SERVICE
#
#          # ?????? ??? ??? ?? ???? ???(??? ??)
#          predicates:
#            - Path=/first-service/**
#
#          # ?? ??? ? ???? ???? /first-serivce?? ??? ???? ?? ??? ?? ?? ??? ??
#          filters:
#            - RewritePath=/first-service/(?<segment>.*), /$\{segment}
#            - AddRequestHeader=first-request, first-request-header
#            - AddResponseHeader=first-response, first-response-header
#
#        - id: 2st-service
#          uri: lb://2ST-SERVICE
#          predicates:
#            - Path=/second-service/**
#          filters:
#            - RewritePath=/second-service/(?<segment>.*), /$\{segment}
#            - AddRequestHeader=second-request, second-request-header
#            - AddResponseHeader=second-response, second-response-header

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://SWCAMP-USER-SERVICE
          predicates:
            - Path=/user-service/**
            - Method=GET
          filters:
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter
        - id: user-service
          uri: lb://SWCAMP-USER-SERVICE
          predicates:
            - Path=/user-service/**
            - Method=POST
          filters:
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
        - id: order-service
          uri: lb://SWCAMP-ORDER-SERVICE
          predicates:
            - Path=/order-service/**
          filters:
            - RewritePath=/order-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter

token:
  secret: K0HHLFxls3IXU9tafT999JvEC3c80Dhy7qv41YyY99Pe1agCbJyiv558uBWHTQiYzRDdju9/CLtZltizLjGgSQ==