server:
  port: 8761


eureka:
  client:

#    eureka server? eureka server? ??? ? ??? ??.
    register-with-eureka: false

#   eureka server? ?? micro service? ????? ???? ?? ??? ??? ??.
    fetch-registry: false
