server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      
      # ????? ?? localrepository? ??
      server:
        git:
          uri: file:///C:\lecture\09_msa\config
