services:
  springboot-app:
    build:
      context: ./chap01_01_bootProject
      dockerfile: Dockerfile
    image: ys0915/boot_9_project:v2
    container_name: boot-container
    ports:
      - "8055:7777"
    networks:
      - camp-net
  
  vue-app:
    build:
      context: ./chap01_02_vueProject
      dockerfile: Dockerfile
    image: ys0915/vue_9_project:v2
    container_name: vue-container
    ports:
      - "8011:5173"
    networks:
      - camp-net

# 네트워크 드라이버 옵션
# 1. driver: bridge -> 기본 값, 대부분의 경우에 적합
# 2. driver: host -> 호스트 네트워크를 직접 사용, 성능은 좋지만 보안에 취약
# 3. driver: none -> 네트워크 기능 없음, 완전히 격리된 환경
networks:
  camp-net:
    driver: bridge